/*
** EPITECH PROJECT, 2023
** B-OOP-400-BDX-4-1-arcade-melissa.laget
** File description:
** IFrameBuffer.hpp
*/

#pragma once

#include <iostream>

namespace arcade {
    enum STATUS {
        FAILURE = -1,
        EXIT = 0,// exit arcade
        RUNNING = 1,
        OPTION = 2,
    };

    enum OPTIONS {
        LOAD_GRAPH = 0,
        LOAD_GAME = 1,
        RESTART = 2,
        QUIT = 3,// quit game (back to main menu)
    };

    enum EVENT {
        ARCADE_KEY_A,
        ARCADE_KEY_B,
        ARCADE_KEY_C,
        ARCADE_KEY_D,
        ARCADE_KEY_E,
        ARCADE_KEY_F,
        ARCADE_KEY_G,
        ARCADE_KEY_H,
        ARCADE_KEY_I,
        ARCADE_KEY_J,
        ARCADE_KEY_K,
        ARCADE_KEY_L,
        ARCADE_KEY_M,
        ARCADE_KEY_N,
        ARCADE_KEY_O,
        ARCADE_KEY_P,
        ARCADE_KEY_Q,
        ARCADE_KEY_R,
        ARCADE_KEY_S,
        ARCADE_KEY_T,
        ARCADE_KEY_U,
        ARCADE_KEY_V,
        ARCADE_KEY_W,
        ARCADE_KEY_X,
        ARCADE_KEY_Y,
        ARCADE_KEY_Z,
        ARCADE_KEY_1,
        ARCADE_KEY_2,
        ARCADE_KEY_3,
        ARCADE_KEY_4,
        ARCADE_KEY_5,
        ARCADE_KEY_6,
        ARCADE_KEY_7,
        ARCADE_KEY_8,
        ARCADE_KEY_9,
        ARCADE_KEY_0,
        ARCADE_KEY_RIGHT,
        ARCADE_KEY_LEFT,
        ARCADE_KEY_UP,
        ARCADE_KEY_DOWN,
        ARCADE_KEY_SPACE,
        ARCADE_KEY_ENTER,
        ARCADE_KEY_ESC,
        ARCADE_KEY_TAB,
        ARCADE_KEY_SHIFT,
        ARCADE_KEY_CTRL,
        ARCADE_KEY_ALT,
        ARCADE_SYS_MENU,
        ARCADE_SYS_NEXT_DISPLAY,
        ARCADE_SYS_PREV_DISPLAY,
        ARCADE_SYS_NEXT_GAME,
        ARCADE_SYS_PREV_GAME,
        ARCADE_SYS_EXIT,
        ARCADE_SYS_RESTART,
        ARCADE_WIN_CLOSE,
    };

    enum Characters {
        // chars
        ZERO,
        ONE,
        TWO,
        THREE,
        FOUR,
        FIVE,
        SIX,
        SEVEN,
        EIGHT,
        NINE,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        QUESTION_MARK,
        EXCLAMATION_MARK,
        COMMA,
        PERIOD,
        HASHTAG,
        PLUS,
        MINUS,
        ASTERISK,
        COLON,
        SEMICOLON,
        UNDERSCORE,
        DOLLAR,
        EQUALS,
        LEFT_PARENTHESIS,
        RIGHT_PARENTHESIS,
        PERCENT,
        // shapes
        DOT,
        SMALL_DOT,
        EMPTY_CIRCLE,
        FULL_CIRCLE,
        EMPTY_SQUARE,
        FULL_SQUARE,
        EMPTY_STAR,
        ARROW_UP,
        ARROW_DOWN,
        ARROW_LEFT,
        ARROW_RIGHT,
        BOX_HORIZONTAL_LINE,
        BOX_VERTICAL_LINE,
        BOX_TOP_LEFT_CORNER,
        BOX_TOP_RIGHT_CORNER,
        BOX_BOTTOM_LEFT_CORNER,
        BOX_BOTTOM_RIGHT_CORNER,
        BOX_LEFT_T,
        BOX_RIGHT_T,
        BOX_TOP_T,
        BOX_BOTTOM_T,
        BOX_CROSS,
        BOX_DOUBLE_HORIZONTAL_LINE,
        BOX_DOUBLE_VERTICAL_LINE,
        BOX_DOUBLE_TOP_LEFT_CORNER,
        BOX_DOUBLE_TOP_RIGHT_CORNER,
        BOX_DOUBLE_BOTTOM_LEFT_CORNER,
        BOX_DOUBLE_BOTTOM_RIGHT_CORNER,
        BOX_DOUBLE_LEFT_T,
        BOX_DOUBLE_RIGHT_T,
        BOX_DOUBLE_TOP_T,
        BOX_DOUBLE_BOTTOM_T,
        BOX_DOUBLE_CROSS,
        EMPTY_TRIANGLE_LEFT,
        EMPTY_TRIANGLE_RIGHT,
        EMPTY_TRIANGLE_UP,
        EMPTY_TRIANGLE_DOWN,
        FULL_TRIANGLE_LEFT,
        FULL_TRIANGLE_RIGHT,
        FULL_TRIANGLE_UP,
        FULL_TRIANGLE_DOWN,
        FULL_BLOCK,
        CROSS,
        CHECK,
        SMALL_CIRCLE,
        SLASH,
        BACKSLASH,
        AND_SIGN,
        AT_SIGN,
        DOUBLE_QUOTE,
        SINGLE_QUOTE,
        LEFT_ANGLE_BRACKET,
        RIGHT_ANGLE_BRACKET,
        TILDE,
        PIPE,
        FULL_FLAG,
        COOL_ARROW,
        RELOAD,
        LIGHTNING,
        MULTIPLY_SIGN,
        FULL_STAR,
        NULL_CHR,
    };

    enum LibType {
        GRAPHICAL,
        GAME,
    };

};// namespace arcade
